print("Welcome to the tip calculator")
bill=input("What was the total bill?")
b=float(bill)
per=input("What percentage would you like to give?")
p=int(per)
split=input("How many people to split the bill")
s=int(split)
total=((b/s)*p)
t= float(total)
r=round(t,2)
print(f"Each person should pay:{r}")